CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email varchar(255) NOT NULL UNIQUE,
    username varchar(255) NOT NULL UNIQUE,
    firstname TINYTEXT NOT NULL,
    lastname TINYTEXT NOT NULL,
    dob DATE,
    password TINYTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)